version: "3.8"

services:

  webserver:
    image: arcapi:latest
    ports:
      - 8888:8888

  solr:
    image: ubuntu-solr:latest
    volumes:
      - nlidb:/home/app/project-dir/solr-8.10.1/server/solr
    expose:
      - 8983
    ports:
      - 8983:8983

volumes:
  nlidb:
